name: Run Crypto & Forex Scrapers

on:
  schedule:
    - cron: "*/1 * * * *"   # اجرای خودکار هر 2 دقیقه
  workflow_dispatch:        # اجرا دستی

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests
        pip install beautifulsoup4

    - name: Run Crypto Scraper
      run: python index.py

    - name: Run Forex Scraper
      run: python stoke_script.py

    - name: Commit updated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"

        git add arzdigital_data.txt || true
        git add qoute_price.txt || true

        git commit -m "Auto-update crypto & forex data" || echo "No changes to commit"

        git push
